name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Transfer tests via SCP
      run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} tests a08trb41@login.g100.cineca.it:~
