name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Transfer tests via SCP
      run: |
        sshpass -p "${{ secrets.SSH_PRIVATE_KEY }}" scp tests a08trb41@login.g100.cineca.it:~
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY }}

